# https://github.com/andreashuber69/eslint-config/blob/master/README.md#----andreashuber69eslint-config
os: linux
dist: xenial
language: node_js
node_js:
- 16

script:
- npm run ci

deploy:
  provider: npm
  email:
    secure: IEn1OCyjNVNyCriX5mVZVCkLYpGAzcenMSGbxMZyhUsNTRr4btDHEJQIU588IcYJBO460QBUPO8QzVBCCma1//szpvtbXXdXCizB3/gFHKJSxOyvgSUN2FkoaKbu8IWmpiytu2YafHKxbBpwTTxujew7jupClZhiT1PsXRFpQnUGnzwKp06N81G6TFhNkdOkPCk1DzzytLSXhakeUEuJBgMDpD1qIHe9DYqP4TibTxdJa69BbdzUBt8Qw8+cjD2AvUfb5GGkbSV4ekuBHWzBqld96uNeKoMeJ5AZCfUEA4h20GvLjLwmh7cichggoJX4cdu8EYYKwnt5jogyIdFspa8xrtYRYtXG74oBs9N/QX2mzSvT8Qj7/ShMgHd6mCjfIFGxfmpGoPRFVJWgP61MqyAjRtA5qkwvf/0HazNPQShp7eFoqTjcbO8tmK07AXQHAn/JjEz3Dl/D1NayFHZGk63VxPn8I7ttf1lC0jV+viLrYCNclvxVCXXML8iHb6s5sHvOKeKlr0kUEKyaLMwqKAVpKWF0rE0GeizqYLsmbV+OdUUirbXgP3VujqpqlE6NIIGsIoOAgGpa78L1/RDYAThyCpNnx56CLGF2MCylSOUSIDiNe+qb46KrtlwpDJ4krp17Ot8+Y088GNdZklYEaHDv0sPthcULXOqyT5+PeCs=
  api_token:
    secure: hnEhGSL0cgc3l12peUzlisWFjthU99OyCjJL2o6zc+r+6IOvFvxCehq2WL7rYksR9W5/xbVODGpo05A/QZGtO9cJPsRcMzCZ4VCB8Cg3vkFpSWURe1IAHGZUx9UOAv+gdZ+WEAZMzqNFGYedlLM73aBUbiRWDdLY7WDJ1Gp4mPLfqJF/26UVWzPSohoJUmW8QGCr8+WSWDTUvHYEuKjntQI+EtZ3ZSQeLIgV97eeNem1GFBDYYnhHSp4Lhx/WFTPpvxh5KmUI2x1z2nytwDS5dW9RneczXPf6LGgOzbvZ3DP4KeaSI6rkL1JkJbLMZrl1FGwHlVeXqMVAuxlGyLpDwkoISQ3w9VrPvBvAwgyX4hQjCYvGR2xlYiQcWkqmTeAvstZbhf7xfMmUSn87Nr4kStFMO0Lr/kc2DpjyTG4De9cU2zc2hlRQxPXV62o/H3sXpw9OswR4wy0PIEU2p5XRrdNaVX0NI4tuaiTFpwV+M91AGZraX1Uc9ZfUbqACeLd8qTASzYqvbSKVjxDTuLq8fVzPx18EQNdYUbzxxsRj982QUeOV4Kj7OYIvGjRscos5H5yx0VDpRR4QU47xAD6UrBZj1NtVyupKZ0nkZSzCVRRmH7RKeH/pwkZM+gQVqEWAHIsAmtzQsvdqn2RiUxMdwX7e76X0vSRZIw/Gk0btTE=
  on:
    branch: master

notifications:
  email:
    recipients:
      secure: b0N0YHZ2Ay2GMKbQOApGhPezQwXhS5AyWtfuemiXJdsftNxDvdgiwhvlaHvLVh6ckFz12H0SzfeTZURPJ87sWeCzt1s7/b8Onq4rL0kI5c/KsDsPlyoDjQ6BQMmMsFbEuUDTDiidPYb1avWwd6MtjTt7cunhAPDMNlGfmcr2cw36tMMHMgTxwNx848/0Xqsxn/OmqicYZt3oRNFLXv90yhcxCH377iOW2tqeyItT36uzNby/SPfUz/xI8FJug3Om7UsDlWc2Ca5IqJLb+5NrQYgn6+0bXZc1+WXbFbznm8PlZOPVcwFlQI2DlmC0qCzY23eh4QV+WyPsT/FRIbUzjf4bZbo6fklUEpX9Tt/LkLXnqpGh54qvdXPrdEmVe/zLI9rZloZ6YeOqXjxYdQS7kf9S/YL3yDdmY+dbeYJJfuA6Me+/Pz4SZgOjDelt8IAqJ0MRgLKkaef4G6uuhztRFOwz7dGM8z8GBxPWijCSkKmBWJiITHSQXcOjNH3/D/ObBNG3qIve8m5TAwPA2YYKiSGc2fk0/t51etzfqhfkFUhTSPjJgGF5ZRB52D5wb4jag5bgSBwc0OUGFEI5YflPLKs1MipaPJLk5Dv0c5oWF2cgCCW65OAIs0EVrnAAl4ctskReFXR0gOXAELZEEC6huFL1tWumPPb0NO73aeQjINM=
